import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "sweetalert2/src/sweetalert2.scss";
import "react-calendar/dist/Calendar.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ToastContainer limit={1} theme="dark" />
        {children}
      </body>
    </html>
  );
}
